### ISSUE TITLE
Can't log in

### ISSUE THREAD

**Issue by AstudilloMarillo** [level3tjg/RedditFilter#15] opened 2024-04-28 18:03 UTC
I keep getting the message: 'Something went wrong. Try again later.'
Just trying to log in with username / password.

**Comment by level3tjg** [comment] 2024-04-29 01:06
Are you jailbroken or did you sideload the app?

**Comment by AstudilloMarillo** [comment] 2024-04-29 07:56
> Are you jailbroken or did you sideload the app?

I sideloaded the app

**Comment by Fridodo** [comment] 2024-04-29 19:04
same here sideloaded throug altstore and cant login

**Comment by level3tjg** [comment] 2024-04-29 20:21
Will check this out soon, in the meantime you can log in by connecting another account (Google or Apple) and logging in through that account.

**Comment by level3tjg** [comment] 2024-05-04 01:31
Fixed in [v2024.18.0-1.1.5](https://github.com/level3tjg/RedditFilter/releases/tag/v2024.18.0-1.1.5)

**Closed by level3tjg** 2024-05-04 01:31 UTC

**Comment by level3tjg** [comment] 2024-05-09 17:38
> While the 'Something went wrong. Try again later.' message is now gone, I still can't login. I enter my correct account information, but now I get the message 'Incorrect username or password' even though it is, in fact, correct. Tried with multiple accounts.

I'm not able to reproduce this at all, I tried multiple accounts as well. You're welcome to create a new issue, it may be helpful if other users are experiencing the same thing.

**Comment by AstudilloMarillo** [comment] 2024-05-10 15:11
> I'm not able to reproduce this at all, I tried multiple accounts as well. You're welcome to create a new issue, it may be helpful if other users are experiencing the same thing.

I don't know why it didn't work before, I definitely checked that the login info was correct. I tried it now once again and now it did work. I finally managed to log in 🙂.
