### ISSUE TITLE
can't log in (but i can on official reddit)

### ISSUE THREAD

**Issue by ComfortableMilk4454** [level3tjg/RedditFilter#26] opened 2024-08-15 10:50 UTC
using https://github.com/level3tjg/RedditFilter/releases/download/v2024.26.0-1.1.6/RedditFilter_2024.26.0-1.1.6.ipa, tells me wrong password even though im filling it from 1password the exact same way i did on official reddit v2024.33.0 when i tested a minute ago. iOS 17.6.1, iPhone 13 mini. sideloaded iPA through maplesign.

**Comment by level3tjg** [comment] 2024-08-17 15:17
duplicate of #20

**Closed by level3tjg** 2024-08-17 15:17 UTC

**Comment by ComfortableMilk4454** [comment] 2024-08-19 22:42
resolved itself, thanks
